"""updated

Revision ID: abcef4e7acd6
Revises: 1a660c242acb
Create Date: 2024-02-05 00:25:49.481118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcef4e7acd6'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
